async function fetchCryptoData(symbol) {
    try {
        const response = await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}USDT&interval=1w&limit=8`);
        const data = await response.json();

        // Calcul du total des taux de variation sur 8 semaines
        let totalVariation = 0;

        // Mise à jour du tableau avec les données et la couleur
        const cryptoRow = document.getElementById(symbol);

        for (let i = 0; i < data.length; i++) {
            const openPrice = parseFloat(data[i][1]);
            const closePrice = parseFloat(data[i][4]);
            const weeklyVariation = ((closePrice - openPrice) / openPrice) * 100;
            const cellIndex = i + 1; // Décalage d'une cellule pour éviter la première cellule (Crypto)

            const variationCell = cryptoRow.insertCell(cellIndex);
            const variationValue = weeklyVariation.toFixed(2);
            const weekStartDate = new Date(data[i][0]);
            const weekEndDate = new Date(data[i][6]);
            const options = { year: '2-digit', month: '2-digit', day: '2-digit' };
            variationCell.textContent = `${weekStartDate.toLocaleDateString('fr-FR', options)} - ${weekEndDate.toLocaleDateString('fr-FR', options).slice(0, 5)}: ${variationValue}%`;

            // Ne pas ajouter de classe de couleur aux cellules individuelles
            totalVariation += weeklyVariation; // Ajouter la variation hebdomadaire au total
        }

        // Ajouter la cellule pour afficher le total de variation
        const totalCell = cryptoRow.insertCell(data.length + 1);
        const totalValue = totalVariation.toFixed(2);
        totalCell.textContent = `${totalValue}%`;

        if (totalVariation >= 100) {
            totalCell.classList.add('positive');
        } else if (totalVariation <= -100) {
            totalCell.classList.add('negative');
        }

        if (totalVariation >= 100 || totalVariation <= -100) {
            // Ajouter le nom de la crypto en dehors du tableau
            const cryptoNameDiv = document.getElementById('cryptoNames');
            const cryptoName = document.createElement('p');
            cryptoName.textContent = `${symbol} : ${totalValue}%`;
            cryptoNameDiv.appendChild(cryptoName);

            // Ajouter la classe CSS appropriée
            if (totalVariation >= 100) {
                cryptoName.classList.add('positive');
            } else if (totalVariation <= -100) {
                cryptoName.classList.add('negative');
            }
        }
    } catch (error) {
        console.error(`Erreur lors de la récupération des données pour ${symbol}:`, error);
    }
}

// Appel de la fonction pour obtenir les taux de variation des cryptos
fetchCryptoData('1INCH');
fetchCryptoData('AAVE');
fetchCryptoData('ACA');
fetchCryptoData('ACH');
fetchCryptoData('ACM');
fetchCryptoData('ADA');
fetchCryptoData('ADX');
fetchCryptoData('AERGO');
fetchCryptoData('AGIX');
fetchCryptoData('AGLD');
fetchCryptoData('AKRO');
fetchCryptoData('ALCX');
fetchCryptoData('ALGO');
fetchCryptoData('ALICE');
fetchCryptoData('ALPACA');
fetchCryptoData('ALPHA');
fetchCryptoData('ALPINE');
fetchCryptoData('AMB');
fetchCryptoData('AMP');
fetchCryptoData('ANKR');
fetchCryptoData('ANT');
fetchCryptoData('APE');
fetchCryptoData('API3');
fetchCryptoData('APT');
fetchCryptoData('ARB');
fetchCryptoData('ARDR');
fetchCryptoData('ARKM');
fetchCryptoData('ARPA');
fetchCryptoData('AR');
fetchCryptoData('ASR');
fetchCryptoData('ASTR');
fetchCryptoData('AST');
fetchCryptoData('ATA');
fetchCryptoData('ATM');
fetchCryptoData('ATOM');
fetchCryptoData('AUCTION');
fetchCryptoData('AUDIO');
fetchCryptoData('AVA');
fetchCryptoData('AVAX');
fetchCryptoData('AXS');
fetchCryptoData('BADGER');
fetchCryptoData('BAKE');
fetchCryptoData('BAL');
fetchCryptoData('BAND');
fetchCryptoData('BAR');
fetchCryptoData('BAT');
fetchCryptoData('BCH');
fetchCryptoData('BEL');
fetchCryptoData('BETA');
fetchCryptoData('BICO');
fetchCryptoData('BIFI');
fetchCryptoData('BLZ');
fetchCryptoData('BNB');
fetchCryptoData('BNT');
fetchCryptoData('BNX');
fetchCryptoData('BOND');
fetchCryptoData('BSW');
fetchCryptoData('BTC');
fetchCryptoData('BTS');
fetchCryptoData('BTTC');
fetchCryptoData('BURGER');
fetchCryptoData('BUSD');
fetchCryptoData('C98');
fetchCryptoData('CAKE');
fetchCryptoData('CELO');
fetchCryptoData('CELR');
fetchCryptoData('CFX');
fetchCryptoData('CHESS');
fetchCryptoData('CHR');
fetchCryptoData('CHZ');
fetchCryptoData('CITY');
fetchCryptoData('CKB');
fetchCryptoData('CLV');
fetchCryptoData('COMBO');
fetchCryptoData('COMP');
fetchCryptoData('COS');
fetchCryptoData('COTI');
fetchCryptoData('CRV');
fetchCryptoData('CTK');
fetchCryptoData('CTSI');
fetchCryptoData('CTXC');
fetchCryptoData('CVC');
fetchCryptoData('CVP');
fetchCryptoData('CVX');
fetchCryptoData('CYBER');
fetchCryptoData('DAR');
fetchCryptoData('DASH');
fetchCryptoData('DATA');
fetchCryptoData('DCR');
fetchCryptoData('DEGO');
fetchCryptoData('DENT');
fetchCryptoData('DEXE');
fetchCryptoData('DF');
fetchCryptoData('DGB');
fetchCryptoData('DIA');
fetchCryptoData('DOCK');
fetchCryptoData('DODO');
fetchCryptoData('DOGE');
fetchCryptoData('DOT');
fetchCryptoData('DREP');
fetchCryptoData('DUSK');
fetchCryptoData('DYDX');
fetchCryptoData('EDU');
fetchCryptoData('EGLD');
fetchCryptoData('ELF');
fetchCryptoData('ENJ');
fetchCryptoData('ENS');
fetchCryptoData('EOS');
fetchCryptoData('EPX');
fetchCryptoData('ERN');
fetchCryptoData('ETC');
fetchCryptoData('ETH');
fetchCryptoData('EUR');
fetchCryptoData('FARM');
fetchCryptoData('FDUSD');
fetchCryptoData('FET');
fetchCryptoData('FIDA');
fetchCryptoData('FIL');
fetchCryptoData('FIO');
fetchCryptoData('FIRO');
fetchCryptoData('FIS');
fetchCryptoData('FLM');
fetchCryptoData('FLOKI');
fetchCryptoData('FLOW');
fetchCryptoData('FLUX');
fetchCryptoData('FORTH');
fetchCryptoData('FOR');
fetchCryptoData('FRONT');
fetchCryptoData('FTM');
fetchCryptoData('FUN');
fetchCryptoData('FXS');
fetchCryptoData('GALA');
fetchCryptoData('GAL');
fetchCryptoData('GAS');
fetchCryptoData('GBP');
fetchCryptoData('GHST');
fetchCryptoData('GLMR');
fetchCryptoData('GLM');
fetchCryptoData('GMT');
fetchCryptoData('GMX');
fetchCryptoData('GNO');
fetchCryptoData('GNS');
fetchCryptoData('GRT');
fetchCryptoData('GTC');
fetchCryptoData('HARD');
fetchCryptoData('HBAR');
fetchCryptoData('HFT');
fetchCryptoData('HIFI');
fetchCryptoData('HIGH');
fetchCryptoData('HOT');
fetchCryptoData('ICP');
fetchCryptoData('ICX');
fetchCryptoData('IDEX');
fetchCryptoData('ID');
fetchCryptoData('ILV');
fetchCryptoData('IMX');
fetchCryptoData('INJ');
fetchCryptoData('IOST');
fetchCryptoData('IOTA');
fetchCryptoData('IOTX');
fetchCryptoData('IRIS');
fetchCryptoData('JASMY');
fetchCryptoData('JOE');
fetchCryptoData('JST');
fetchCryptoData('JUV');
fetchCryptoData('KAVA');
fetchCryptoData('KDA');
fetchCryptoData('KEY');
fetchCryptoData('KLAY');
fetchCryptoData('KMD');
fetchCryptoData('KNC');
fetchCryptoData('KP3R');
fetchCryptoData('KSM');
fetchCryptoData('LAZIO');
fetchCryptoData('LDO');
fetchCryptoData('LEVER');
fetchCryptoData('LINA');
fetchCryptoData('LINK');
fetchCryptoData('LIT');
fetchCryptoData('LOKA');
fetchCryptoData('LOOM');
fetchCryptoData('LPT');
fetchCryptoData('LQTY');
fetchCryptoData('LRC');
fetchCryptoData('LSK');
fetchCryptoData('LTC');
fetchCryptoData('LTO');
fetchCryptoData('LUNA');
fetchCryptoData('LUNC');
fetchCryptoData('MAGIC');
fetchCryptoData('MANA');
fetchCryptoData('MASK');
fetchCryptoData('MATIC');
fetchCryptoData('MAV');
fetchCryptoData('MBL');
fetchCryptoData('MBOX');
fetchCryptoData('MC');
fetchCryptoData('MDT');
fetchCryptoData('MDX');
fetchCryptoData('MINA');
fetchCryptoData('MKR');
fetchCryptoData('MLN');
fetchCryptoData('MOB');
fetchCryptoData('MOVR');
fetchCryptoData('MTL');
fetchCryptoData('MULTI');
fetchCryptoData('NEAR');
fetchCryptoData('NEO');
fetchCryptoData('NEXO');
fetchCryptoData('NKN');
fetchCryptoData('NMR');
fetchCryptoData('NULS');
fetchCryptoData('OAX');
fetchCryptoData('OCEAN');
fetchCryptoData('OGN');
fetchCryptoData('OG');
fetchCryptoData('OMG');
fetchCryptoData('OM');
fetchCryptoData('ONE');
fetchCryptoData('ONG');
fetchCryptoData('ONT');
fetchCryptoData('OOKI');
fetchCryptoData('OP');
fetchCryptoData('ORN');
fetchCryptoData('OSMO');
fetchCryptoData('OXT');
fetchCryptoData('PAXG');
fetchCryptoData('PENDLE');
fetchCryptoData('PEOPLE');
fetchCryptoData('PEPE');
fetchCryptoData('PERL');
fetchCryptoData('PERP');
fetchCryptoData('PHA');
fetchCryptoData('PHB');
fetchCryptoData('PLA');
fetchCryptoData('PNT');
fetchCryptoData('POLS');
fetchCryptoData('POLYX');
fetchCryptoData('POND');
fetchCryptoData('PORTO');
fetchCryptoData('POWR');
fetchCryptoData('PROM');
fetchCryptoData('PROS');
fetchCryptoData('PSG');
fetchCryptoData('PUNDIX');
fetchCryptoData('PYR');
fetchCryptoData('QI');
fetchCryptoData('QKC');
fetchCryptoData('QNT');
fetchCryptoData('QTUM');
fetchCryptoData('QUICK');
fetchCryptoData('RAD');
fetchCryptoData('RARE');
fetchCryptoData('RAY');
fetchCryptoData('RDNT');
fetchCryptoData('REEF');
fetchCryptoData('REI');
fetchCryptoData('REN');
fetchCryptoData('REQ');
fetchCryptoData('RIF');
fetchCryptoData('RLC');
fetchCryptoData('RNDR');
fetchCryptoData('ROSE');
fetchCryptoData('RPL');
fetchCryptoData('RSR');
fetchCryptoData('RUNE');
fetchCryptoData('RVN');
fetchCryptoData('SAND');
fetchCryptoData('SANTOS');
fetchCryptoData('SCRT');
fetchCryptoData('SC');
fetchCryptoData('SEI');
fetchCryptoData('SFP');
fetchCryptoData('SHIB');
fetchCryptoData('SKL');
fetchCryptoData('SLP');
fetchCryptoData('SNT');
fetchCryptoData('SNX');
fetchCryptoData('SOL');
fetchCryptoData('SPELL');
fetchCryptoData('SSV');
fetchCryptoData('STEEM');
fetchCryptoData('STG');
fetchCryptoData('STMX');
fetchCryptoData('STORJ');
fetchCryptoData('STPT');
fetchCryptoData('STRAX');
fetchCryptoData('STX');
fetchCryptoData('SUI');
fetchCryptoData('SUN');
fetchCryptoData('SUPER');
fetchCryptoData('SUSHI');
fetchCryptoData('SXP');
fetchCryptoData('SYN');
fetchCryptoData('SYS');
fetchCryptoData('TFUEL');
fetchCryptoData('THETA');
fetchCryptoData('TKO');
fetchCryptoData('TLM');
fetchCryptoData('TOMO');
fetchCryptoData('TRB');
fetchCryptoData('TROY');
fetchCryptoData('TRU');
fetchCryptoData('TRX');
fetchCryptoData('T');
fetchCryptoData('TUSD');
fetchCryptoData('TVK');
fetchCryptoData('TWT');
fetchCryptoData('UFT');
fetchCryptoData('UMA');
fetchCryptoData('UNFI');
fetchCryptoData('UNI');
fetchCryptoData('USDC');
fetchCryptoData('USDP');
fetchCryptoData('USTC');
fetchCryptoData('UTK');
fetchCryptoData('VET');
fetchCryptoData('VGX');
fetchCryptoData('VIB');
fetchCryptoData('VIDT');
fetchCryptoData('VITE');
fetchCryptoData('VOXEL');
fetchCryptoData('VTHO');
fetchCryptoData('WAN');
fetchCryptoData('WAVES');
fetchCryptoData('WAXP');
fetchCryptoData('WBETH');
fetchCryptoData('WBTC');
fetchCryptoData('WING');
fetchCryptoData('WIN');
fetchCryptoData('WLD');
fetchCryptoData('WNXM');
fetchCryptoData('WOO');
fetchCryptoData('WRX');
fetchCryptoData('WTC');
fetchCryptoData('XEC');
fetchCryptoData('XEM');
fetchCryptoData('XLM');
fetchCryptoData('XMR');
fetchCryptoData('XNO');
fetchCryptoData('XRP');
fetchCryptoData('XTZ');
fetchCryptoData('XVG');
fetchCryptoData('XVS');
fetchCryptoData('YFI');
fetchCryptoData('YGG');
fetchCryptoData('ZEC');
fetchCryptoData('ZEN');
fetchCryptoData('ZIL');
fetchCryptoData('ZRX');